name: Django CI

on:
  push:
    branches: 
      - main

  pull_request:
    branches: 
      - main

jobs:
  ci:
    name: Continuos Integration
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://pyprojatdjfly:pyprojatdjfly@localhost:5432/pyprojatdjfly

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: pyprojatdjfly
          POSTGRES_USER: pyprojatdjfly
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11.2
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.2'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup .env
      run: cp .env.example .env

    - name: Run Tests
      run: |
        python manage.py test

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: ci
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/fly-actions/setup-fly@master
      - run: fly deploy --remote-only
